# ruff configuration file
target-version = "py311"
line-length = 88
fix = true
show-fixes = true

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "N",   # pep8-naming
    "S",   # flake8-bandit
    "T20", # flake8-print
    "SIM", # flake8-simplify
]

ignore = [
    "E501",  # line too long, handled by formatter
    "B008",  # do not perform function calls in argument defaults
    "S101",  # use of assert detected
    "T20",   # allow print statements for now
]

[lint.per-file-ignores]
"tests/*" = ["S101", "T20", "S113", "F401"]  # Allow assert, print, requests timeout, and unused imports in tests

[lint.isort]
force-single-line = false
known-first-party = ["app", "tests"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
